spring:
  application:
    name: customer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/xuancong-ecommerce

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/customer
    username: admin
    password: admin

server:
  port: 8003

keycloak:
  auth-server-url: http://localhost:8080
  realm: ecommerce
  credentials:
    secret: ahqmyjKC0HLq2dYMv49upP43hBDsl6CB
  client-id: xuancong-ecommerce
  bearer-only: true
  public-client: false
  ssl-required: none
  cors: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG

debug: true