#version: "3.9"
services:
  postgres:
    image: debezium/postgres:16-alpine
#    tìm file docker file trong thư mục postgres để build
#    build: ./docker/postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./docker/postgres/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
      - postgres:/var/lib/postgresql/data
#    command: postgres -c 'max_connections=500'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - lexuancong-network

  pgadmin:
    image: dpage/pgadmin4:2024-10-19-2
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: xuancong@admin.com
      PGADMIN_DEFAULT_PASSWORD: xuancong
    networks:
      - lexuancong-network


#  authentication by keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.2
#    chạy ở môi trường dev , không yêu cầu cao như mt product
    command: 'start-dev --import-realm'
    environment:
      KEYCLOAK_ADMIN: lexuancong
      KEYCLOAK_ADMIN_PASSWORD: lexuancong
#      kết nối tới db để lưu thông tin đăng nhập như phiên , token
      KC_DB: postgres
#      khi image này chạy thì nó là container như 1 mt riêng biệt , nếu localhost thay cho post.. thì localhost ở đây là chính nó nên sai
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: xuancong
      KC_DB_PASSWORD: xuancong
      JAVA_OPTS: "-Dkeycloak.profile=preview"

      #      cho nó chạy cổng 80 trong container
      KC_HTTP_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - lexuancong-network
    volumes:
      - ./custom-theme-keycloak/themes/e-commerce/theme:/opt/keycloak/themes
      - ./docker/keycloak/realm/realm-config-export.json:/opt/keycloak/data/import/realm-export.json

  nginx:
    image: nginx:1.27.2
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./docker/nginx/config/nginx_api_gateway_config.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
    networks:
      - lexuancong-network





networks:
#  các service có cùng mạng thì cos thể kết nối với nhau
  lexuancong-network:
    driver: bridge
    name: lexuancong-network

volumes:
  postgres:
  pgadmin:
  redis:





